# Generated by Django 5.0.4 on 2024-05-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters_app.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='theater_performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters_app.theaterperformance', verbose_name='theater_performance'),
        ),
    ]
